# Generated by Django 3.1.6 on 2021-09-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='role',
            field=models.CharField(default='cus', max_length=10),
            preserve_default=False,
        ),
    ]
