# Generated by Django 3.1.6 on 2021-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0003_auto_20210911_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trans',
            fields=[
                ('account', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=15)),
                ('balance', models.CharField(max_length=20)),
                ('date', models.DateField()),
            ],
        ),
    ]
