# Generated by Django 3.1.6 on 2021-09-11 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
