# Generated by Django 3.1.6 on 2021-09-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_auto_20210911_1530'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trans',
            new_name='Transact',
        ),
    ]
