# Generated by Django 3.1.6 on 2021-09-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
